'use strict';

const YELP_CLIENT_ID = 'INSERT_STRING_HERE';
const YELP_CLIENT_SECRET = 'INSERT_STRING_HERE';
const FB_PAGE_ACCESS_TOKEN = 'INSERT_STRING_HERE';
const FB_VERIFY_TOKEN = 'INSERT_STRING_HERE';
const WIT_AI_ACCESS_TOKEN = 'INSERT_STRING_HERE';

module.exports = {
  FB_PAGE_ACCESS_TOKEN,
  FB_VERIFY_TOKEN,
  YELP_CLIENT_ID,
  YELP_CLIENT_SECRET,
  WIT_AI_ACCESS_TOKEN,
};
